In [1]:
import numpy as np

In [29]:
import tensorflow as tf

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X = iris.data

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
y = iris.target

In [16]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
# class 0 --> [1,0,0]
# class 1 --> [0,1,0]
# class 2 --> [0,0,1]


In [11]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [17]:
y = to_categorical(y)
y.shape


(150, 3)

In [19]:
# y

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size= 0.33, random_state=42)

In [22]:
from sklearn.preprocessing import MinMaxScaler

In [23]:
# np.array([5,10,15,20])/20
scaler_object = MinMaxScaler()

In [24]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [25]:
scaled_X_train = scaler_object.transform(X_train)

In [26]:
scaled_X_test = scaler_object.transform(X_test)

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [33]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation = 'relu'))
model.add(Dense(8,input_dim=4,activation = 'relu'))
model.add(Dense(3,activation = 'softmax'))
model.compile(loss='categorical_crossentropy',optimizer = 'adam', metrics = ['accuracy'])


In [34]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

Train on 100 samples
Epoch 1/150
100/100 - 6s - loss: 1.1270 - accuracy: 0.4300
Epoch 2/150
100/100 - 0s - loss: 1.1228 - accuracy: 0.3700
Epoch 3/150
100/100 - 0s - loss: 1.1194 - accuracy: 0.3600
Epoch 4/150
100/100 - 0s - loss: 1.1161 - accuracy: 0.3500
Epoch 5/150
100/100 - 0s - loss: 1.1129 - accuracy: 0.3500
Epoch 6/150
100/100 - 0s - loss: 1.1101 - accuracy: 0.3500
Epoch 7/150
100/100 - 0s - loss: 1.1069 - accuracy: 0.3500
Epoch 8/150
100/100 - 0s - loss: 1.1042 - accuracy: 0.3500
Epoch 9/150
100/100 - 0s - loss: 1.1014 - accuracy: 0.3500
Epoch 10/150
100/100 - 0s - loss: 1.0985 - accuracy: 0.3500
Epoch 11/150
100/100 - 0s - loss: 1.0952 - accuracy: 0.3500
Epoch 12/150
100/100 - 0s - loss: 1.0917 - accuracy: 0.3500
Epoch 13/150
100/100 - 0s - loss: 1.0877 - accuracy: 0.3500
Epoch 14/150
100/100 - 0s - loss: 1.0840 - accuracy: 0.3500
Epoch 15/150
100/100 - 0s - loss: 1.0799 - accuracy: 0.3500
Epoch 16/150
100/100 - 0s - loss: 1.0760 - accuracy: 0.3500
Epoch 17/150
100/100 - 0s - 

Epoch 137/150
100/100 - 0s - loss: 0.5083 - accuracy: 0.6700
Epoch 138/150
100/100 - 0s - loss: 0.5064 - accuracy: 0.6800
Epoch 139/150
100/100 - 0s - loss: 0.5044 - accuracy: 0.6800
Epoch 140/150
100/100 - 0s - loss: 0.5025 - accuracy: 0.6800
Epoch 141/150
100/100 - 0s - loss: 0.5005 - accuracy: 0.6600
Epoch 142/150
100/100 - 0s - loss: 0.4986 - accuracy: 0.6600
Epoch 143/150
100/100 - 0s - loss: 0.4971 - accuracy: 0.6600
Epoch 144/150
100/100 - 0s - loss: 0.4953 - accuracy: 0.6600
Epoch 145/150
100/100 - 0s - loss: 0.4936 - accuracy: 0.6600
Epoch 146/150
100/100 - 0s - loss: 0.4918 - accuracy: 0.6600
Epoch 147/150
100/100 - 0s - loss: 0.4900 - accuracy: 0.6600
Epoch 148/150
100/100 - 0s - loss: 0.4884 - accuracy: 0.6600
Epoch 149/150
100/100 - 0s - loss: 0.4867 - accuracy: 0.6600
Epoch 150/150
100/100 - 0s - loss: 0.4851 - accuracy: 0.6600


In [37]:
model.predict_classes(scaled_X_test)

array([2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0,
       0, 2, 2, 2, 2, 2], dtype=int64)

In [38]:
# y_test

In [39]:
predictions = model.predict_classes(scaled_X_test)

In [40]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [41]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0,  0, 15],
       [ 0,  0, 16]], dtype=int64)

In [42]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.00      0.00      0.00        15
           2       0.52      1.00      0.68        16

    accuracy                           0.70        50
   macro avg       0.51      0.67      0.56        50
weighted avg       0.55      0.70      0.60        50



C:\Users\VenkyTheGreat\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [43]:
accuracy_score(y_test.argmax(axis=1),predictions)


0.7

In [44]:
model.save('myfirstmodel.h5')

In [47]:
from tensorflow.keras.models import load_model

In [48]:
new_model = load_model('myfirstmodel.h5')

In [49]:
new_model.predict_classes(scaled_X_test)

array([2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0,
       0, 2, 2, 2, 2, 2], dtype=int64)