In [9]:
1+1

2

In [10]:
3+2


5

In [53]:
import tensorflow.compat.v1 as tf


In [54]:
graph1 = tf.Graph()


In [55]:
with graph1.as_default():
    a = tf.constant([2], name = 'constant_a')
    b = tf.constant([3], name = 'constant_b')


In [56]:
a

<tf.Tensor 'constant_a:0' shape=(1,) dtype=int32>

In [58]:
# Printing the value of a
sess = tf.Session(graph = graph1)
result = sess.run(a)
print(result)
sess.close()


[2]


In [59]:
with graph1.as_default():
    c = tf.add(a, b)
    #c = a + b is also a way to define the sum of the terms


In [60]:
sess = tf.Session(graph = graph1)


In [61]:
result = sess.run(c)
print(result)


[5]


In [64]:
sess.close()


In [65]:
with tf.Session(graph = graph1) as sess:
    result = sess.run(c)
    print(result)


[5]


In [66]:
graph2 = tf.Graph()
with graph2.as_default():
    Scalar = tf.constant(2)
    Vector = tf.constant([5,6,2])
    Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
with tf.Session(graph = graph2) as sess:
    result = sess.run(Scalar)
    print ("Scalar (1 entry):\n %s \n" % result)
    result = sess.run(Vector)
    print ("Vector (3 entries) :\n %s \n" % result)
    result = sess.run(Matrix)
    print ("Matrix (3x3 entries):\n %s \n" % result)
    result = sess.run(Tensor)
    print ("Tensor (3x3x3 entries) :\n %s \n" % result)


Scalar (1 entry):
 2 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



In [67]:
Scalar.shape


TensorShape([])

In [68]:
Tensor.shape


TensorShape([3, 3, 3])

In [69]:
graph3 = tf.Graph()
with graph3.as_default():
    Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

    add_1_operation = tf.add(Matrix_one, Matrix_two)
    add_2_operation = Matrix_one + Matrix_two

with tf.Session(graph =graph3) as sess:
    result = sess.run(add_1_operation)
    print ("Defined using tensorflow function :")
    print(result)
    result = sess.run(add_2_operation)
    print ("Defined using normal expressions :")
    print(result)
    

Defined using tensorflow function :
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Defined using normal expressions :
[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [70]:
graph4 = tf.Graph()
with graph4.as_default():
    Matrix_one = tf.constant([[2,3],[3,4]])
    Matrix_two = tf.constant([[2,3],[3,4]])

    mul_operation = tf.matmul(Matrix_one, Matrix_two)

with tf.Session(graph = graph4) as sess:
    result = sess.run(mul_operation)
    print ("Defined using tensorflow function :")
    print(result)


Defined using tensorflow function :
[[13 18]
 [18 25]]


In [71]:
v = tf.Variable(0)


In [72]:
update = tf.assign(v, v+1)
update


<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=1>

In [73]:
init_op = tf.global_variables_initializer()

In [74]:
with tf.Session() as session:
    session.run(init_op)
    print(session.run(v))
    for _ in range(3):
        session.run(update)
        print(session.run(v))


RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

In [75]:
a = tf.placeholder(tf.float32)


RuntimeError: tf.placeholder() is not compatible with eager execution.