In [1]:
import pandas as pd

In [2]:
npr = pd.read_csv('npr.csv')

In [40]:
# npr['Article'][0]

# len(npr)


In [4]:
# Preprocessing

from sklearn.feature_extraction.text import CountVectorizer


In [5]:
cv = CountVectorizer(max_df = 0.90, min_df = 2,stop_words = 'english')

In [6]:
dtm = cv.fit_transform(npr['Article'])

In [7]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [8]:
from sklearn.decomposition import LatentDirichletAllocation

In [11]:
LDA = LatentDirichletAllocation(n_components = 7, random_state = 42)

In [12]:
LDA.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [13]:
# Grab the vocabulary of words
# Grab the topics
# Grab the highest proability words per topic

In [14]:
len(cv.get_feature_names())

54777

In [16]:
type(cv.get_feature_names())

list

In [20]:
import random
random_word_id = random.randint(0,54777)
cv.get_feature_names()[10]


'01'

In [21]:
len(LDA.components_)

7

In [22]:
type(LDA.components_)

numpy.ndarray

In [23]:
LDA.components_.shape

(7, 54777)

In [24]:
single_topic = LDA.components_[0]
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [28]:
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [31]:
top_twenty_words = single_topic.argsort()[-20:]

In [32]:
for index in top_twenty_words:
    print(cv.get_feature_names()[index])


president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


In [33]:
for index,topic in enumerate(LDA.components_):
    print(f"THE TOP 15 WORDS FOR TOPIC #(i)")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')


THE TOP 15 WORDS FOR TOPIC #(i)
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']




THE TOP 15 WORDS FOR TOPIC #(i)
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']




THE TOP 15 WORDS FOR TOPIC #(i)
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




THE TOP 15 WORDS FOR TOPIC #(i)
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']




THE TOP 15 WORDS FOR TOPIC #(i)
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




THE TOP 15 WORDS FOR TOPIC #(i)
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 't

In [25]:
import numpy as np

In [26]:
arr = np.array([10,200,1])

In [27]:
arr.argsort()

array([2, 0, 1], dtype=int64)

In [34]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [35]:
npr

Article
0      In the Washington of 2016, even when the polic...
1        Donald Trump has used Twitter  —   his prefe...
2        Donald Trump is unabashedly praising Russian...
3      Updated at 2:50 p. m. ET, Russian President Vl...
4      From photography, illustration and video, to d...
...                                                  ...
11987  The number of law enforcement officers shot an...
11988    Trump is busy these days with victory tours,...
11989  It’s always interesting for the Goats and Soda...
11990  The election of Donald Trump was a surprise to...
11991  Voters in the English city of Sunderland did s...

[11992 rows x 1 columns]

In [36]:
topic_results = LDA.transform(dtm)

In [37]:
topic_results.shape

(11992, 7)

In [38]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [42]:
topic_results[0].argmax()

1

In [43]:
npr['Topic'] = topic_results.argmax(axis=1)

In [44]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]